---
- name: Adding NGINX signing key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: Installing NGINX
  apt:
    pkg: nginx
    state: latest

- name: Removing default NGINX config
  file: name=/etc/nginx/sites-enabled/default state=absent

- name: Install system NGINX config
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Starting NGINX
  service:
    name: nginx
    state: started
