---
- name: Update cache
  apt:
    update_cache: yes
  tags:
    - dependencies

- name: Update safe packages
  apt:
   upgrade: safe
  tags:
    - dependencies

- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - htop
    - python-certbot-nginx
    - mosh
    - vim
    - zsh
  tags:
    - dependencies
